### ISSUE TITLE
Usability problem - help needed as the default response for a call without parameters

### ISSUE THREAD

**Issue by Laci1953** [jayacotton/find#10]
It would be very nice & useful to get help typed back if find.com is called without any parameter ( e.g. A>find<CR> )
Currently, you get no help feedback, but a list of files...
This "default" help "feedback" it's a basic feature of many CP/M utilities, and it's easy to implement.
Thanks!

**Comment by jayacotton** [comment]
Made a small change to the u.i. processing.  If you say find with no parameters, you get a help message.

**Comment by feilipu** [comment]
Tested on 8085. Works as expected.

**Comment by Laci1953** [comment]
Fixed!
Thanks Jay!

**Comment by Laci1953** [comment]
Tested on Z80. It's OK.Ladislau

    On Thursday, March 3, 2022, 05:03:40 AM GMT+2, Phillip Stevens ***@***.***> wrote:  
 
 


Tested on 8085. Works as expected.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
